# Generated by Django 5.2.7 on 2025-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ID_Paciente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Tipo_Documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('Numero_Documento', models.IntegerField(unique=True)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Genero', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.CharField(blank=True, max_length=100, null=True)),
                ('Estado_Civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('D', 'Divorciado/a')], max_length=2)),
                ('Fecha_Registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
    ]
