# Generated by Django 5.2.7 on 2025-11-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['Nombre']},
        ),
    ]
