# Generated by Django 5.2.7 on 2025-11-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Medica',
            fields=[
                ('ID_Area', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Area', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Area_Medica',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('ID_Medico', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Especialidad', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.CharField(max_length=100)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.area_medica')),
            ],
            options={
                'db_table': 'Medico',
            },
        ),
    ]
