# Generated by Django 5.2.7 on 2025-11-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0002_alter_paciente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('ID_Medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Presentacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Medicamento',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('ID_Receta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Receta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Receta',
            fields=[
                ('ID_Detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Dosis', models.CharField(max_length=100)),
                ('Frecuencia', models.CharField(max_length=100)),
                ('Duracion', models.CharField(max_length=100)),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.medicamento')),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'Detalle_Receta',
            },
        ),
    ]
