# Generated by Django 5.2.7 on 2025-11-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0002_alter_paciente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('ID_Factura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Emision', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('ID_Detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Cantidad', models.IntegerField()),
                ('Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
            options={
                'db_table': 'Detalle_Factura',
            },
        ),
    ]
