# Generated by Django 5.2.7 on 2025-11-09 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0003_alter_paciente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Sistema',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=50, unique=True)),
                ('Contraseña', models.CharField(max_length=255)),
                ('Rol', models.CharField(max_length=50)),
                ('Medico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.medico')),
                ('Paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Usuario_Sistema',
            },
        ),
    ]
