# Generated by Django 5.2.7 on 2025-11-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('ID_Cita', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Motivo', models.TextField()),
                ('Estado', models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente'), ('En espera', 'En espera')], max_length=50)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Cita',
            },
        ),
    ]
