# Generated by Django 5.2.7 on 2025-11-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0002_alter_paciente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen_Laboratorio',
            fields=[
                ('ID_Examen', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Examen', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Resultado', models.TextField(blank=True, null=True)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Examen_Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('ID_Historia', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Apertura', models.DateField()),
                ('Observaciones_Generales', models.TextField(blank=True, null=True)),
                ('Paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Historia_Clinica',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('ID_Diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Descripcion', models.TextField()),
                ('Historia_Clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.historia_clinica')),
            ],
            options={
                'db_table': 'Diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('ID_Tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
                ('Duracion', models.CharField(max_length=100)),
                ('Diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.diagnostico')),
            ],
            options={
                'db_table': 'Tratamiento',
            },
        ),
    ]
