# Generated by Django 5.2.7 on 2025-11-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen_laboratorio',
            name='Archivo',
            field=models.ImageField(blank=True, null=True, upload_to='Imganes_reultados/'),
        ),
        migrations.AddField(
            model_name='examen_laboratorio',
            name='Historia_Clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='historial.historia_clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examen_laboratorio',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
