# Generated by Django 5.2.7 on 2025-11-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_historia_clinica_medico'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='Medico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
    ]
