# Generated by Django 5.2.7 on 2025-11-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0003_alter_paciente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('ID_Habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=10)),
                ('Tipo', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Habitacion',
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('ID_Hospitalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Ingreso', models.DateField()),
                ('Fecha_Salida', models.DateField(blank=True, null=True)),
                ('Motivo', models.TextField()),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.habitacion')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'Hospitalizacion',
            },
        ),
    ]
